### ISSUE TITLE
Komplettering

### ISSUE THREAD

**Issue by simonlindholm** [inda18plusplus/alandr-filestorage#1]
Sorry for the long delay in reviewing this... generally it looks quite good, just one crypto-related thing I'll ask you to fix: when the client downloads a file, it doesn't look like it verifies its hash. (Which is quite silly, given that both uploads and deletes do so :) )

Also, some other feedback which you don't have to address but might be useful anyway:
- You're using manual `new[]`/`delete[]` in C++; don't. Use `std::vector` (preferably) or `std::unique_ptr`.
- Your key derivation function is fast, which makes brute-forcing possible. Ideally it would use something like [scrypt](https://en.wikipedia.org/wiki/Scrypt) or [Argon2](https://en.wikipedia.org/wiki/Argon2).
- It's a bit sad that the client has to download all the hashes, initially. It could take a lot of time for a large file server, and makes the Merkle tree kind of pointless. :) It's possible to make do without them, and have the server send over hashes along the path to the leaf on demand, which would make individual file reads/writes more efficient.
- `Node::createTree` has a rather complicated base case; could use an initialization function which isn't a member function to cut down on the complexity
- `SSLWrap`'s Packet class can easily read/write out of bounds, causing security vulnerabilities if you used it in real-world code.

**Comment by AlbinAndreasson** [comment]
The crypto stuff should be fixed now. Key derivation now takes ~3 seconds on my machine.

**Comment by simonlindholm** [comment]
> ```c++
> 	p >> ret >> topHash >> f;
> 	if(topHash != _tree.topHash()) {
> 		std::cerr << "The server tophash doesn't match own!\n\n";
> 	}
> ```
That's not enough verification; the server could send a correct top hash, but still lie about file contents.

**Comment by AlbinAndreasson** [comment]
Shite. I think this check is functional

**Comment by simonlindholm** [comment]
Closer. You have to use your previously stored hash somehow, though -- that's the only means you have of authenticating data.

**Comment by AlbinAndreasson** [comment]
So, before I start coding; I check if the server's old tophash is valid, insert the file into the tree, and then check again? Thus verifying that the file the server send was the one used to calculate the previous top hash.

**Comment by simonlindholm** [comment]
That sounds about right.

**Comment by AlbinAndreasson** [comment]
Third time's the charm...?

**Comment by simonlindholm** [comment]
Looks better! (Note that you didn't actually need to send over `topHash`.)
